build_image:
  image: docker:git

  services:
  - docker:dind

  tags:
  - docker

  script:
  - docker build -t ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle .
  - docker push ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle

test:
  image: ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle

  tags:
  - stylechecker
  
  script:
  - Dummy Script
