image: docker:git

services:
  - docker:dind

build_image:
  tags:
  - docker

  script:
  - docker build -t programmieren-hiwis/checkstyle-ips:testing .
  #- docker push programmieren-hiwis/checkstyle-ips:testing

test_image:
  tags:
  - docker

  script:
  - docker run programmieren-hiwis/checkstyle-ips:testing TestFile.java
