build_image:
  image: docker:git

  services:
  - docker:dind

  tags:
  - docker

  script:
  - docker build -t ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips .
  - docker push ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips

test:
  image: ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips

  tags:
  - stylechecker
  
  script:
  - java -jar /checkstyle/checkstyle.jar -c /checkstyle/tubs_checks.xml -o out .

  artifacts:
    paths:
    - out
    expire_in: 1 week
