image: docker:git

services:
  - docker:dind

build_image:
  tags:
  - docker

  script:
  - docker build -t ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips:testing .
  - docker push ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips:testing

test_image:
  tags:
  - docker

  script:
  - docker run ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips:testing TestFile.java
