image: docker:git

services:
  - docker:dind

build_image:
  tags:
  - docker

  script:
  - docker build -t checkstyle-ips:testing .

test:
  tags:
  - stylechecker

  #script:
  #- java -jar checkstyle.jar -c tubs_checks.xml TestFile.java
