build_image:
  image: docker:git

  services:
  - docker:dind

  tags:
  - docker

  before_script:
  - docker info

  stage: build

  script:
  - docker build -t checkstyle .
  - docker run checkstyle
  - docker tag checkstyle ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle .
  - docker push ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle

test:
  image: ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle

  tags:
  - stylechecker
  
  script:
  - Dummy Script
