image: docker:git
services:
  - docker:dind

build:
  tags:
  - docker
  script:
  - docker build -t ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips .
  - docker push ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips

test:
  script:
    - Dummy Script
