build_image:
  image: docker:latest

  services:
  - docker:dind

  tags:
  - docker

  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ips1.ibr.cs.tu-bs.de:5005

  stage: build

  script:
  - docker build -t ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle:latest .
  - docker push ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle:latest

test:
  image: ips1.ibr.cs.tu-bs.de:5005/abgabesystem/checkstyle:latest

  tags:
  - stylechecker
  
  script:
  - Dummy Script
