build_image:
  image: docker:git

  services:
  - docker:dind

  tags:
  - docker

  script:
  - docker build -t checkstyle-ips .

test:
  image: ips1.ibr.cs.tu-bs.de:5005/programmieren-hiwis/checkstyle-ips

  tags:
  - stylechecker

  script:
  - java -jar checkstyle.jar -c tubs_checks.xml TestFile.java
